#### numpy : provides high-performance multidimensional array object

##### array
- grid of homogeneous values
- indexed by tuple of ints
- rank : number of dimensions
- shape : tuple of ints


### array creation


#### 1-D array

In [11]:
import numpy as np

a = np.array([1, 2, 3, 4, 5]) # rank 1 array
print(f"a : {a}")
print(f"a.shape : {a.shape} row x column")
print(f"a.ndim also rank: {a.ndim}")
print(f"a.dtype : {a.dtype}")
print(f"a.size : {a.size}")
print(f"a.itemsize : {a.itemsize}")
print(f"a.nbytes : {a.nbytes}")
print(f"a.data : {a.data}")
print(f"a.flags : {a.flags}")
print("---")

a : [1 2 3 4 5]
a.shape : (5,) row x column
a.ndim also rank: 1
a.dtype : int64
a.size : 5
a.itemsize : 8
a.nbytes : 40
a.data : <memory at 0x7f8f9a2290c0>
a.flags :   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

---


#### 2-D array

In [12]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) # rank 2 array
print(f"b : {b}")
print(f"b.shape : {b.shape} , row x col")
print(f"b.ndim also rank: {b.ndim}")
print(f"b.dtype : {b.dtype}")
print(f"b.size : {b.size}")
print(f"b.itemsize : {b.itemsize}")
print(f"b.nbytes : {b.nbytes}")
print(f"b.data : {b.data}")
print(f"b.flags : {b.flags}")
print("---")

b : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
b.shape : (2, 5) , row x col
b.ndim also rank: 2
b.dtype : int64
b.size : 10
b.itemsize : 8
b.nbytes : 80
b.data : <memory at 0x7f8f9a75f030>
b.flags :   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

---


#### functions to create arrays

In [13]:
# np.zeroes((row,col), dtype=float)) 
a = np.zeros((2, 3)) # rank 2 array
print(f"a : {a}")

a : [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# np.ones((row,col), dtype=float))
b = np.ones((2, 3)) # rank 2 array
print(f"b : {b}")

b : [[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# np.full((row,col), value, dtype=float))
c = np.full((2, 3), 9) # rank 2 array
print(f"c : {c}")

c : [[9 9 9]
 [9 9 9]]


In [17]:
# np.eye(x) : creates an identity matrix of size x times x
d = np.eye(3) # rank 2 array
print(f"d : {d}")

d : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# np.random.random((row,col), dtype=float)) : creates a random array of size row x col
e = np.random.random((2, 3)) # rank 2 array
print(f"e : {e}")


e : [[0.0777603  0.12773271 0.91918806]
 [0.25679501 0.92738817 0.60518808]]


In [26]:
# np.arange(start[including], stop[excluding], step) 
f = np.arange(0, 10, 2) # rank 1 array
print(f"f : {f}")


f : [0 2 4 6 8]


In [28]:
# np.linspace(start[including], stop[including], space) : creates an array of num evenly spaced values between start and stop
g = np.linspace(0, 10, 11) # rank 1 array
print(f"g : {g}")

g : [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [65]:
# np.random.randint(low, high[excluding], size) : creates an array of random integers between low and high
h = np.random.randint(2, 4, 5) # rank 1 array
print(f"h : {h}")

h : [3 2 3 3 3]


### array indexing


#### slicing
- A slice of an array is a view into the same data, so modifying it will modify the original array.

In [68]:
# slicing syntax : a[start[including]:stop[excluding]:step]
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(f"a : {a}")

b = a[2:4] # slicing
print(f"b : {b}")


a : [0 1 2 3 4 5 6 7 8 9]
b : [2 3]


In [70]:
b [0] = 10 # change value
print(f"b : {b}")
print(f"a : {a}") # a will change because b is a view of a

b : [10  3]
a : [ 0  1 10  3  4  5  6  7  8  9]


#### 2-D slicing

In [71]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"two_d_array : {two_d_array}")

print(f"two_d_array[0] : {two_d_array[0]}")
print(f"two_d_array[0][0] : {two_d_array[0][0]}")


two_d_array : [[1 2 3]
 [4 5 6]]
two_d_array[0] : [1 2 3]
two_d_array[0][0] : 1


#### integer array indexing


In [78]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(f"a : {a}")

print(f"a[[0, 1, 1], [0, 1, 0]] : {a[[0, 1, 1], [0, 1, 0]]}")

# The above example of integer array indexing is equivalent to this:
print(f"np.array([a[0, 0], a[1, 1], a[1, 0]]) : {np.array([a[0, 0], a[1, 1], a[1, 0]])}") 

a : [[1 2 3]
 [4 5 6]]
a[[0, 1, 1], [0, 1, 0]] : [1 5 4]
np.array([a[0, 0], a[1, 1], a[1, 0]]) : [1 5 4]


#### boolean array indexing
-  used to select the elements of an array that satisfy some condition

In [85]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(f"a : {a}")

print(f"a[a > 2] : {a[a > 2]}")
print(f"a[a % 2 ==0] : {a[a % 2 == 0]}")

a : [[1 2 3]
 [4 5 6]]
a[a > 2] : [3 4 5 6]
a[a % 2 ==0] : [2 4 6]


### datatypes


In [87]:
# list all the datatypes in numpy
print(f"np.sctypeDict : {np.sctypeDict}")


np.sctypeDict : {'?': <class 'numpy.bool_'>, 0: <class 'numpy.bool_'>, 'byte': <class 'numpy.int8'>, 'b': <class 'numpy.int8'>, 1: <class 'numpy.int8'>, 'ubyte': <class 'numpy.uint8'>, 'B': <class 'numpy.uint8'>, 2: <class 'numpy.uint8'>, 'short': <class 'numpy.int16'>, 'h': <class 'numpy.int16'>, 3: <class 'numpy.int16'>, 'ushort': <class 'numpy.uint16'>, 'H': <class 'numpy.uint16'>, 4: <class 'numpy.uint16'>, 'i': <class 'numpy.int32'>, 5: <class 'numpy.int32'>, 'uint': <class 'numpy.uint64'>, 'I': <class 'numpy.uint32'>, 6: <class 'numpy.uint32'>, 'intp': <class 'numpy.int64'>, 'p': <class 'numpy.int64'>, 7: <class 'numpy.int64'>, 'uintp': <class 'numpy.uint64'>, 'P': <class 'numpy.uint64'>, 8: <class 'numpy.uint64'>, 'long': <class 'numpy.int64'>, 'l': <class 'numpy.int64'>, 'L': <class 'numpy.uint64'>, 'longlong': <class 'numpy.longlong'>, 'q': <class 'numpy.longlong'>, 9: <class 'numpy.longlong'>, 'ulonglong': <class 'numpy.ulonglong'>, 'Q': <class 'numpy.ulonglong'>, 10: <class 

In [90]:
x = np.array([1, 2, 3, 4, 5])
print(f"x : {x}, x.dtype : {x.dtype}")

x = np.array([1.2, 2.3, 3.4, 4.5, 5.6])
print(f"x : {x}, x.dtype : {x.dtype}")

x : [1 2 3 4 5], x.dtype : int64
x : [1.2 2.3 3.4 4.5 5.6], x.dtype : float64


##### force a particular type





In [91]:
x = np.array([1, 2], dtype=np.int64)
print(f"x : {x}, x.dtype : {x.dtype}")



x : [1 2], x.dtype : int64


### array math

- Basic mathematical functions operate elementwise on arrays, 
- and are available both as operator overloads and as functions in the numpy module:

In [92]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])

print(f"x : {x}, x.dtype : {x.dtype}")
print(f"y : {y}, y.dtype : {y.dtype}")
print(f"x+y : {x+y}")
print(f"x-y : {x-y}")
print(f"x*y : {x*y}")
print(f"x/y : {x/y}")
print(f"x//y : {x//y}")
print(f"x%y : {x%y}")
print(f"x**y : {x**y}")

x : [1 2 3 4 5], x.dtype : int64
y : [ 6  7  8  9 10], y.dtype : int64
x+y : [ 7  9 11 13 15]
x-y : [-5 -5 -5 -5 -5]
x*y : [ 6 14 24 36 50]
x/y : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
x//y : [0 0 0 0 0]
x%y : [1 2 3 4 5]
x**y : [      1     128    6561  262144 9765625]


##### as functions

In [93]:
x  = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])

print(f"x+y : {np.add(x, y)}")
print(f"x-y : {np.subtract(x, y)}")
print(f"x*y : {np.multiply(x, y)}")
print(f"x/y : {np.divide(x, y)}")
print(f"x//y : {np.floor_divide(x, y)}")
print(f"x%y : {np.mod(x, y)}")
print(f"x**y : {np.power(x, y)}")


x+y : [ 7  9 11 13 15]
x-y : [-5 -5 -5 -5 -5]
x*y : [ 6 14 24 36 50]
x/y : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
x//y : [0 0 0 0 0]
x%y : [1 2 3 4 5]
x**y : [      1     128    6561  262144 9765625]


#### useful functions


In [94]:
# dot
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# np.dot : dot product of two arrays
print(f"np.dot(x, y) : {np.dot(x, y)}")


np.dot(x, y) : [[19 22]
 [43 50]]


In [95]:
# sum
x = np.array([[1, 2], [3, 4]])
print(f"np.sum(x) : {np.sum(x)}")
print(f"np.sum(x, axis=0) : {np.sum(x, axis=0)}")
print(f"np.sum(x, axis=1) : {np.sum(x, axis=1)}")


np.sum(x) : 10
np.sum(x, axis=0) : [4 6]
np.sum(x, axis=1) : [3 7]


In [96]:
# transpose

x = np.array([[1, 2], [3, 4]])
print(f"x : {x}")
print(f"x.T : {x.T}")


x : [[1 2]
 [3 4]]
x.T : [[1 3]
 [2 4]]


### Broadcasting
- powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.