## Creating Array

- I love you mor sunu

In [2]:
import numpy as np
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [3]:
type(array)

numpy.ndarray

In [4]:
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(f"b : {b}")
print(f"b.shape : {b.shape} , row x col")
print(f"b.ndim also rank: {b.ndim}")
print(f"b.dtype : {b.dtype}")
print(f"b.size : {b.size}")
print(f"b.itemsize : {b.itemsize}")
print(f"b.nbytes : {b.nbytes}")
print(f"b.data : {b.data}")
print(f"b.flags : {b.flags}")
print("---")

b : [[1 2 3]
 [4 5 6]]
b.shape : (2, 3) , row x col
b.ndim also rank: 2
b.dtype : int64
b.size : 6
b.itemsize : 8
b.nbytes : 48
b.data : <memory at 0x787650937850>
b.flags :   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

---


In [6]:
# np.zeroes((row,col), dtype=float)) 
a = np.zeros((2, 3)) # rank 2 array
print(f"a : {a}")

a : [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# np.ones((row,col), dtype=float))
b = np.ones((2, 3)) # rank 2 array
print(f"b : {b}")

b : [[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# np.full((row,col), value, dtype=float))
c = np.full((2, 3), 9) # rank 2 array
print(f"c : {c}")

c : [[9 9 9]
 [9 9 9]]


In [9]:
# np.eye(x) : creates an identity matrix of size x times x
d = np.eye(3) # rank 2 array
print(f"d : {d}")

d : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
# np.random.random((row,col), dtype=float)) : creates a random array of size row x col
e = np.random.random((2, 3)) # rank 2 array
print(f"e : {e}")

e : [[0.83010408 0.0400319  0.12803599]
 [0.83128154 0.16273407 0.309807  ]]


In [38]:
# np.arange(start[including], stop[excluding], step) 
f = np.arange(0, 10, 2) # rank 1 array
print(f"f : {f}")


f : [0 2 4 6 8]


## indexing

In [40]:
a = 5
print(f"a : {a**2}")

a : 25


In [43]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

In [44]:
print(f"a : {a}")
print(f"b : {b}")


a : [1 2 3 4 5]
b : [10 20 30 40 50]


In [50]:
a ** b

array([                   1,              1048576,      205891132094649,
                          0, -6776596920136667815])